"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class image_points_2d_t(object):
    __slots__ = ["utime", "num_points", "axis_1", "axis_2"]

    def __init__(self):
        self.utime = 0
        self.num_points = 0
        self.axis_1 = []
        self.axis_2 = []

    def encode(self):
        buf = BytesIO()
        buf.write(image_points_2d_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qh", self.utime, self.num_points))
        buf.write(struct.pack('>%dq' % self.num_points, *self.axis_1[:self.num_points]))
        buf.write(struct.pack('>%dq' % self.num_points, *self.axis_2[:self.num_points]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != image_points_2d_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return image_points_2d_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = image_points_2d_t()
        self.utime, self.num_points = struct.unpack(">qh", buf.read(10))
        self.axis_1 = struct.unpack('>%dq' % self.num_points, buf.read(self.num_points * 8))
        self.axis_2 = struct.unpack('>%dq' % self.num_points, buf.read(self.num_points * 8))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if image_points_2d_t in parents: return 0
        tmphash = (0x5645c0174a4d5659) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if image_points_2d_t._packed_fingerprint is None:
            image_points_2d_t._packed_fingerprint = struct.pack(">Q", image_points_2d_t._get_hash_recursive([]))
        return image_points_2d_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

