/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class lcm_velocity_t implements lcm.lcm.LCMEncodable
{
    public long utime;
    public double command_v_mps;
    public double position_m[];
    public boolean cycle_start;
 
    public lcm_velocity_t()
    {
        position_m = new double[2];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x761cd5fc6e049c14L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.lcm_velocity_t.class))
            return 0L;
 
        classes.add(lcmtypes.lcm_velocity_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.utime); 
 
        outs.writeDouble(this.command_v_mps); 
 
        for (int a = 0; a < 2; a++) {
            outs.writeDouble(this.position_m[a]); 
        }
 
        outs.writeByte( this.cycle_start ? 1 : 0); 
 
    }
 
    public lcm_velocity_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public lcm_velocity_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.lcm_velocity_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.lcm_velocity_t o = new lcmtypes.lcm_velocity_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.utime = ins.readLong();
 
        this.command_v_mps = ins.readDouble();
 
        this.position_m = new double[(int) 2];
        for (int a = 0; a < 2; a++) {
            this.position_m[a] = ins.readDouble();
        }
 
        this.cycle_start = ins.readByte()!=0;
 
    }
 
    public lcmtypes.lcm_velocity_t copy()
    {
        lcmtypes.lcm_velocity_t outobj = new lcmtypes.lcm_velocity_t();
        outobj.utime = this.utime;
 
        outobj.command_v_mps = this.command_v_mps;
 
        outobj.position_m = new double[(int) 2];
        System.arraycopy(this.position_m, 0, outobj.position_m, 0, 2); 
        outobj.cycle_start = this.cycle_start;
 
        return outobj;
    }
 
}

