"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class relative_position_t(object):
    __slots__ = ["utime", "velocity", "position"]

    def __init__(self):
        self.utime = 0
        self.velocity = 0.0
        self.position = [ 0.0 for dim0 in range(2) ]

    def encode(self):
        buf = BytesIO()
        buf.write(relative_position_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qd", self.utime, self.velocity))
        buf.write(struct.pack('>2d', *self.position[:2]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != relative_position_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return relative_position_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = relative_position_t()
        self.utime, self.velocity = struct.unpack(">qd", buf.read(16))
        self.position = struct.unpack('>2d', buf.read(16))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if relative_position_t in parents: return 0
        tmphash = (0xbceca6b30e5916eb) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if relative_position_t._packed_fingerprint is None:
            relative_position_t._packed_fingerprint = struct.pack(">Q", relative_position_t._get_hash_recursive([]))
        return relative_position_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

