/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class tool_state_t implements lcm.lcm.LCMEncodable
{
    public long utime;
    public double position[];
    public boolean cycle_start;
 
    public tool_state_t()
    {
        position = new double[2];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xc721caaa357bdc0dL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.tool_state_t.class))
            return 0L;
 
        classes.add(lcmtypes.tool_state_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.utime); 
 
        for (int a = 0; a < 2; a++) {
            outs.writeDouble(this.position[a]); 
        }
 
        outs.writeByte( this.cycle_start ? 1 : 0); 
 
    }
 
    public tool_state_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public tool_state_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.tool_state_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.tool_state_t o = new lcmtypes.tool_state_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.utime = ins.readLong();
 
        this.position = new double[(int) 2];
        for (int a = 0; a < 2; a++) {
            this.position[a] = ins.readDouble();
        }
 
        this.cycle_start = ins.readByte()!=0;
 
    }
 
    public lcmtypes.tool_state_t copy()
    {
        lcmtypes.tool_state_t outobj = new lcmtypes.tool_state_t();
        outobj.utime = this.utime;
 
        outobj.position = new double[(int) 2];
        System.arraycopy(this.position, 0, outobj.position, 0, 2); 
        outobj.cycle_start = this.cycle_start;
 
        return outobj;
    }
 
}

