"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class tool_state_t(object):
    __slots__ = ["utime", "position_m", "cycle_start"]

    def __init__(self):
        self.utime = 0
        self.position_m = [ 0.0 for dim0 in range(2) ]
        self.cycle_start = False

    def encode(self):
        buf = BytesIO()
        buf.write(tool_state_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.utime))
        buf.write(struct.pack('>2d', *self.position_m[:2]))
        buf.write(struct.pack(">b", self.cycle_start))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != tool_state_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return tool_state_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = tool_state_t()
        self.utime = struct.unpack(">q", buf.read(8))[0]
        self.position_m = struct.unpack('>2d', buf.read(16))
        self.cycle_start = bool(struct.unpack('b', buf.read(1))[0])
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if tool_state_t in parents: return 0
        tmphash = (0x20b0827b75d583c7) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if tool_state_t._packed_fingerprint is None:
            tool_state_t._packed_fingerprint = struct.pack(">Q", tool_state_t._get_hash_recursive([]))
        return tool_state_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

